### ISSUE TITLE
Statistik aktuell?

### ISSUE THREAD

**Issue by notesjor** [redewiedergabe/corpus#1]
Liebes redewiedergabe-Team,
sind die Statistiken zum Korpus aktuell? Ich habe die Daten mit meinem Programm eingelesen. Für die Dekade 1890 habe ich einen Text mehr (78 anstelle von 77 dokumentierten). Zudem fehlen ein paar hundert Token.
Viele Grüße
Jan Oliver Rüdiger

**Comment by LWeimer** [comment]
@notesjor 
Lieber Jan Oliver Rüdiger,
vielen Dank für die Aufmerksamkeit; in der Dekade 1890 hatten wir wohl eine falsche Zahl eingetragen. Diese haben wir nun geändert. An den Gesamtzahlen ändert sich allerdings nichts, da das fehlende Sample bereits in den Werten einberechnet war.
Danke für die Anfrage und weiterhin viel Spaß bei der Benutzung des Korpus!
Lukas Weimer
