### ISSUE TITLE
Falsches Paper verlinkt

### ISSUE THREAD

**Issue by tnhaider** [redewiedergabe/corpus#3]
Hallo,

Offenbar ist das falsche Paper verlinkt (sowohl oben als auch unten in der Readme).

Der Link geht auf das Royal Society Corpus
http://www.lrec-conf.org/proceedings/lrec2020/pdf/2020.lrec-1.99.pdf

Stattdessen wollt ihr vermutlich auf dieses hier verlinken?
https://www.aclweb.org/anthology/2020.lrec-1.100.pdf

Beste Grüße,
Thomas

**Comment by redewiedergabe** [comment]
Danke für den Hinweis, wurde korrigiert! :-)
